### ISSUE TITLE
Not generating config

### ISSUE THREAD

**Issue by itsdinkd** [Patbox/FabricPlaceholderAPI#5]
fabric, latest api, 1.17.1, latest mod version of BoP

[10:29:11] [Server thread/INFO]: [STDERR]: java.io.FileNotFoundException: ./config/boxofplacholders/config.json (No such file or directory)
[10:29:11] [Server thread/INFO]: [STDERR]: 	at java.base/java.io.FileOutputStream.open0(Native Method)
[10:29:11] [Server thread/INFO]: [STDERR]: 	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:291)
[10:29:11] [Server thread/INFO]: [STDERR]: 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:234)
[10:29:11] [Server thread/INFO]: [STDERR]: 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
[10:29:11] [Server thread/INFO]: [STDERR]: 	at eu.pb4.bof.config.ConfigManager.loadConfig(ConfigManager.java:52)
[10:29:11] [Server thread/INFO]: [STDERR]: 	at eu.pb4.bof.BoxOfPlaceholders.lambda$onInitialize$0(BoxOfPlaceholders.java:25)
[10:29:11] [Server thread/INFO]: [STDERR]: 	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$0(ServerLifecycleEvents.java:37)
[10:29:11] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.handler$fgg000$beforeSetupServer(MinecraftServer.java:14802)
[10:29:11] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
[10:29:11] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)

**Comment by Patbox** [comment]
Wrong repo, you should report it here https://github.com/Patbox/BoxOfPlaceholders
